node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('Testing using node4.6') {
     def appContainer = docker.image('node:4.6')
     appContainer.pull()
     appContainer.inside {
       sh 'cd app && npm install --only=dev'
       sh 'cd app && npm test'
     }
   }
   stage('docker build/push to docker hub') {            
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("simplehuman/archerapp:${commit_id}", 'app')
       app.push()
       app.push('latest')
     }                                     
   }                                       
}                                          
