---
- hosts: all
  remote_user: ubuntu
  become: yes
  vars:
    create_containers: 1
    default_container_name: archer-app 
    default_container_image: simplehuman/archerapp:latest 
    default_ports: 3000:3000

  tasks:
  - name: 10 Install aptitude using apt      
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: 20 Install required system packages    
    apt: name={{ item }} state=latest update_cache=yes
    with_items: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools

  - name: 30 Add Docker GPG apt Key
    apt_key:    
      url: https://download.docker.com/linux/ubuntu/gpg       
      state: present   

  - name: 40 Add Docker Repository     
    apt_repository:      
      repo: deb https://download.docker.com/linux/ubuntu xenial stable
      state: present   

  - name: 50 Update apt and install docker-ce   
    apt: update_cache=yes name=docker-ce state=latest

  - name: 60 Install Docker Module for Python    
    pip:    
      name: docker    
      executable: pip3

  - name: 70 Pull default Docker image   
    docker_image:   
      name: "{{ default_container_image }}"     
      source: pull 

  - name: 80 Create default containers    
    docker_container:      
      name: "{{ default_container_name }}{{ item }}"       
      image: "{{ default_container_image }}"     
      pull: yes 
      state: started 
      ports:
        - "3000:3000"
    with_sequence: count={{ create_containers }} 
    tags:
      - container 

